/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -l UIServer -m -i uiserver.h -a uiserveradaptor_p.h:uiserveradaptor.cpp -- org.kde.KIO.UIServer.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "uiserveradaptor_p.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class UIServerAdaptor
 */

UIServerAdaptor::UIServerAdaptor(UIServer *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

UIServerAdaptor::~UIServerAdaptor()
{
    // destructor
}

bool UIServerAdaptor::copying(int id, const QString &from, const QString &to)
{
    // handle method call org.kde.KIO.UIServer.copying
    return parent()->copying(id, from, to);
}

bool UIServerAdaptor::creatingDir(int id, const QString &url)
{
    // handle method call org.kde.KIO.UIServer.creatingDir
    return parent()->creatingDir(id, url);
}

bool UIServerAdaptor::deleting(int id, const QString &url)
{
    // handle method call org.kde.KIO.UIServer.deleting
    return parent()->deleting(id, url);
}

void UIServerAdaptor::infoMessage(int id, const QString &msg)
{
    // handle method call org.kde.KIO.UIServer.infoMessage
    parent()->infoMessage(id, msg);
}

void UIServerAdaptor::progressInfoMessage(int id, const QString &msg)
{
    // handle method call org.kde.KIO.UIServer.progressInfoMessage
    parent()->progressInfoMessage(id, msg);
}

void UIServerAdaptor::jobFinished(int id)
{
    // handle method call org.kde.KIO.UIServer.jobFinished
    parent()->jobFinished(id);
}

bool UIServerAdaptor::mounting(int id, const QString &dev, const QString &point)
{
    // handle method call org.kde.KIO.UIServer.mounting
    return parent()->mounting(id, dev, point);
}

bool UIServerAdaptor::moving(int id, const QString &from, const QString &to)
{
    // handle method call org.kde.KIO.UIServer.moving
    return parent()->moving(id, from, to);
}

int UIServerAdaptor::newJob(const QString &appServiceName, int capabilities, bool showProgress, const QString &internalAppName, const QString &jobIcon, const QString &appName)
{
    // handle method call org.kde.KIO.UIServer.newJob
    return parent()->newJob(appServiceName, capabilities, showProgress, internalAppName, jobIcon, appName);
}

void UIServerAdaptor::percent(int id, uint ipercent)
{
    // handle method call org.kde.KIO.UIServer.percent
    parent()->percent(id, ipercent);
}

void UIServerAdaptor::processedDirs(int id, uint dirs)
{
    // handle method call org.kde.KIO.UIServer.processedDirs
    parent()->processedDirs(id, dirs);
}

void UIServerAdaptor::processedFiles(int id, uint files)
{
    // handle method call org.kde.KIO.UIServer.processedFiles
    parent()->processedFiles(id, files);
}

void UIServerAdaptor::processedSize(int id, qulonglong size)
{
    // handle method call org.kde.KIO.UIServer.processedSize
    parent()->processedSize(id, size);
}

void UIServerAdaptor::setJobVisible(int id, bool enable)
{
    // handle method call org.kde.KIO.UIServer.setJobVisible
    parent()->setJobVisible(id, enable);
}

void UIServerAdaptor::speed(int id, const QString &bytesPerSecond)
{
    // handle method call org.kde.KIO.UIServer.speed
    parent()->speed(id, bytesPerSecond);
}

bool UIServerAdaptor::stating(int id, const QString &url)
{
    // handle method call org.kde.KIO.UIServer.stating
    return parent()->stating(id, url);
}

void UIServerAdaptor::totalDirs(int id, uint dirs)
{
    // handle method call org.kde.KIO.UIServer.totalDirs
    parent()->totalDirs(id, dirs);
}

void UIServerAdaptor::totalFiles(int id, uint files)
{
    // handle method call org.kde.KIO.UIServer.totalFiles
    parent()->totalFiles(id, files);
}

void UIServerAdaptor::totalSize(int id, qulonglong size)
{
    // handle method call org.kde.KIO.UIServer.totalSize
    parent()->totalSize(id, size);
}

bool UIServerAdaptor::transferring(int id, const QString &url)
{
    // handle method call org.kde.KIO.UIServer.transferring
    return parent()->transferring(id, url);
}

bool UIServerAdaptor::unmounting(int id, const QString &point)
{
    // handle method call org.kde.KIO.UIServer.unmounting
    return parent()->unmounting(id, point);
}


#include "uiserveradaptor_p.moc"
