######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 1 20:09:13 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywritebackplugin.h writebackplugin.h writebackservice.h
SOURCES += mywritebackplugin.cpp writebackplugin.cpp writebackservice.cpp
